config/routes.rb
Rails.application.routes.draw do
  root    'welcome#index'
  get     'contact' => 'static_pages#contact'
  get     'about' => 'static_pages#about'
  get     'help' => 'static_pages#help'
  get     'signup' => 'users#new'
  get     'login'   => 'sessions#new'
  post    'login'   => 'sessions#create'
  delete  'logout'  => 'sessions#destroy'

  resources :recipes do
    resources :ingredients do
    end
  end

  resources :products

  resources :users

end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  has_many :ingredients, dependent: :destroy
  validates :title, presence: true,
                    length: { minimum: 5 }
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  http_basic_authenticate_with name: "dhh", password: "secret", except: [:index, :show]

  def index
    @recipes = Recipe.all
  end

  def new
    @recipe = Recipe.new
    @products = Product.all
  end

  def edit
    @recipe = Recipe.find(params[:id])
  end

  def show
    @recipe = Recipe.find(params[:id])
  end

  def create
    @recipe = Recipe.new(recipe_params)
       
    if @recipe.save
      redirect_to @recipe
    else
      render 'new'
    end
  end

  def update
    @recipe = Recipe.find(params[:id])

    if @recipe.update(recipe_params)
      redirect_to @recipe
    else
      render 'edit'
    end
  end

  def destroy
    @recipe = Recipe.find(params[:id])
    @recipe.destroy

    redirect_to recipes_path
  end

  private
    def recipe_params
      params.require(:recipe).permit(:title, :source, :directions, :review)
    end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_form.html.erb
<%= form_for @recipe do |f| %>
 
  <% if @recipe.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@recipe.errors.count, "error") %> prohibited
        this recipe from being saved:
      </h2>
      <ul>
        <% @recipe.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :source %><br>
    <%= f.text_field :source %>
  </p>

   <p>
    <%= f.label :review %><br>
    <%= f.number_field :review %>
  </p>
 
  <p>
    <%= f.label :directions %><br>
    <%= f.text_area :directions %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
 
<% end %>

app/views/recipes/edit.html.erb
<% provide(:title, "Edit Recipe") %>
<h1>Editing Recipe</h1>

<%= render 'form' %>
<%= link_to 'Back', recipes_path %>

app/views/recipes/index.html.erb
<% provide(:title, "Recipes") %>
<h1>Listing recipes</h1>
 
<%= link_to 'New Recipe', new_recipe_path %>
<table>
  <tr>
      <th>Title</th>
      <th>Source</th>
      <th>Directions</th>
      <th colspan="2"></th>
  </tr>
         
  <% @recipes.each do |recipe| %>
      <tr>
          <td><%= link_to recipe.title, recipe_path(recipe.id) %></td>
          <td><%= recipe.source %></td>
          <td><%= recipe.directions %></td>
          <td><%= link_to 'Edit', edit_recipe_path(recipe) %></td>
          <td><%= link_to 'Delete', recipe_path(recipe),
                    method: :delete,
                    data: { confirm: 'Are you sure?'  } %></td>
      </tr>
  <% end %>
</table>

app/views/recipes/new.html.erb
<% provide(:title, "New Recipe") %>

<h1>New Recipe</h1>

<%= render 'form' %>
<%= link_to 'Back', recipes_path %>

app/views/recipes/show.html.erb
<% provide(:title, "Recipe Details") %>

<p>
  <strong>Title:</strong>
    <%= @recipe.title %>
</p>
 
<p>
  <strong>Source:</strong>
    <%= @recipe.source %>
</p>

<p>
  <strong>Review:</strong>
  <% (1..@recipe.review).each do %>
      *
  <% end %>
<p>
  <strong>Directions:</strong>
    <%= @recipe.directions %>
</p>

<h2>Ingredients</h2>
<ul>
<%= render @recipe.ingredients %>
</ul>

<h2>Add Ingredients</h2>
<%= render 'ingredients/form' %>


<%= link_to 'Edit', edit_recipe_path(@recipe) %>
<%= link_to 'Back', recipes_path %>