config/routes.rb
Rails.application.routes.draw do
  root    'welcome#index'
  get     'contact' => 'static_pages#contact'
  get     'about' => 'static_pages#about'
  get     'help' => 'static_pages#help'
  get     'signup' => 'users#new'
  get     'login'   => 'sessions#new'
  post    'login'   => 'sessions#create'
  delete  'logout'  => 'sessions#destroy'

  resources :recipes do
    resources :ingredients do
    end
  end

  resources :products

  resources :users

end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :ingredients
  validates :name, presence: true,
                  length: { minimum: 3 }
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end

  def new
    @product = Product.new
  end

  def edit
    @product = Product.find(params[:id])
  end

  def show
    @product = Product.find(params[:id])
  end

  def create
    @product = Product.new(product_params)
       
    if @product.save
      redirect_to @product
    else
      render 'new'
    end
  end

  def update
    @product = Product.find(params[:id])

    if @product.update(product_params)
      redirect_to @product
    else
      render 'edit'
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    redirect_to products_path
  end

  private
    def product_params
      params.require(:product).permit(:name)
    end
 end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_for @product do |f| %>
 
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@product.errors.count, "error") %> prohibited
        this product from being saved:
      </h2>
      <ul>
        <% @product.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>

  <!-- TODO add category to product -->

  <p>
    <%= f.submit %>
  </p>
 
<% end %>

app/views/products/edit.html.erb
<% provide(:title, "Edit Product") %>

<h1>Editing Product</h1>

<%= render 'form' %>
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<% provide(:title, "Products") %>
<h1>Listing products</h1>
 
<%= link_to 'New Product', new_product_path %>
<table>
  <tr>
      <th>Title</th>
      <th colspan="2"></th>
  </tr>
         
  <% @products.each do |product| %>
      <tr>
          <td><%= link_to product.name, product_path(product.id) %></td>
          <td><%= link_to 'Edit', edit_product_path(product) %></td>
          <td><%= link_to 'Delete', product_path(product),
                    method: :delete,
                    data: { confirm: 'Are you sure?'  } %></td>
      </tr>
  <% end %>
</table>

app/views/products/new.html.erb
<% provide(:title, "New Product") %>

<h1>New Product</h1>

<%= render 'form' %>
<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<% provide(:title, "Product Details") %>

<p>
  <strong>Name:</strong>
    <%= @product.name %>
</p>
 
<%= link_to 'New', new_product_path(@product) %>
<%= link_to 'Edit', edit_product_path(@product) %>
<%= link_to 'Back', products_path %>